name: CI Simple

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run unit tests
      run: go test -coverage ./...

    - name: Run the static checkers
      run: |
        go vet ./...
        staticcheck ./...
